### ISSUE TITLE
energy::projection()

### ISSUE THREAD

**Issue by whats-in-the-box** [mariarizzo/energy#6]
Hi!

I am following a tutorial for another package, and they used a function `energy::projection()` in one of the steps, but I couldn't find this function in the current version of this package. Was there ever a function `energy::projection()` in older version of this package? Is it deprecated or changed to something different? 

Thank you for any suggestion or help! 

Best Max

**Comment by mariarizzo** [comment]
Hi Max,

This is not in the NAMESPACE of energy. The function projection is an Rcpp function used internally. It is not an Issue because it performs as it is supposed to perform.

https://github.com/mariarizzo/energy/blob/master/src/projection.cpp

You can try to use it this way: (triple colon)

Dx <- as.matrix(dist(rnorm(10)))
Dz <- as.matrix(dist(rnorm(10)))
energy:::projection(Dx, Dz)

This function is part of the programming for partial distance correlation. Now for the standard advice: In general it is  not good practice to depend on internal functions of packages, because when they are internal, they could be modified or replaced without notice.

If you want to see how the function is used, see partial_dcov and partial_dcor in
https://github.com/mariarizzo/energy/blob/master/src/partial-dcor.cpp.

Best,

Maria Rizzo, Professor
Department of Mathematics & Statistics
Bowling Green State University

From: ***@***.***>
Sent: Wednesday, May 25, 2022 6:07 PM
To: ***@***.***>
Cc: ***@***.***>
Subject: [EXTERNAL] [mariarizzo/energy] energy::projection() (Issue #6)


Hi!

I am following a tutorial for another package, and they used a function energy::projection() in one of the steps, but I couldn't find this function in the current version of this package. Was there ever a function energy::projection() in older version of this package? Is it deprecated or changed to something different?

Thank you for any suggestion or help!

Best Max

**Comment by mariarizzo** [comment]
Find this internal function in src/projection.cpp

**Comment by whats-in-the-box** [comment]
Thank you so much! And good advice! 

Best Max
